In [6]:
import numpy as np

In [1]:
a = [3,4,5,6,7]
type(a)

list

In [7]:
b = np.array(a)
b

array([3, 4, 5, 6, 7])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.ndim

1

In [10]:
b.shape

(5,)

In [11]:
c = ([[1,2,3,4,5],
      [6,7,8,9,0],
      [11,12,13,14,15]
      ])
type(c)

list

In [12]:
h = np.array([1,2,4,5])

In [13]:
h

array([1, 2, 4, 5])

In [14]:
m = []
for i in h:
    m.append(i*3)

In [15]:
m

[np.int64(3), np.int64(6), np.int64(12), np.int64(15)]

In [16]:
m = np.array(m)

In [17]:
m

array([ 3,  6, 12, 15])

In [18]:
3*m

array([ 9, 18, 36, 45])